database:
  host: '51.75.125.229'
  port: 3306
  database: 'henebrain'
  username: 'root'
  password: 'uD4kHXXn2W9gFPb'
  pool:
    maximumPoolSize: 10
    minimumIdle: 2
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  migrations:
    enabled: true
    locations: "classpath:db/migration"
  retryPolicy:
    retries: 3
    backoffMs: 250
