allowed-worlds:
  - Hika

debug: false

# Zone de pont cassable (définie via /hb setbroke)
broke:
  pos1:
    world: ~
    x: ~
    y: ~
    z: ~
  pos2:
    world: ~
    x: ~
    y: ~
    z: ~
  reset:
    enabled: true
    batchPerTick: 1500
    snapshotOnLoad: true
