name: Henebrain
version: '${project.version}'
main: io.github.gordoxgit.henebrain.Henebrain
api-version: '1.21'
authors: [GordoxGit]
description: Un plugin de mode de jeu Hikabrain moderne et compétitif.
