name: Henebrain
main: fr.gordox.henebrain.Henebrain
version: 0.1.0
api-version: '1.21'
commands:
  henebrain:
    description: Commande principale du plugin Henebrain
    usage: /<command>
    aliases: [hb]
