name: Henebrain
version: '${project.version}'
main: io.github.gordoxgit.henebrain.Henebrain
api-version: '1.21'
authors: [GordoxGit]
description: Un plugin de mode de jeu Hikabrain moderne et compétitif.
commands:
  hb:
    description: Commandes administratives Henebrain
    usage: /hb db <doctor|migrate>
    permission: henebrain.admin.db
permissions:
  henebrain.admin.db:
    description: Permet d'utiliser les commandes de gestion de la base de données
    default: op
