name: Henebrain
main: com.gordoxgit.henebrain.Henebrain
version: ${project.version}
api-version: '1.21'
author: GordoxGit
commands:
  hb:
    description: Commande principale Henebrain
    usage: /hb
permissions:
  henebrain.admin:
    description: Accès aux commandes d'administration de Henebrain
    default: op
  henebrain.join:
    description: Autorise un joueur à rejoindre une arène
    default: true
