name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'
      - run: gradle build
      - uses: actions/upload-artifact@v3
        with:
          name: Henebrain
          path: build/libs/Henebrain-0.1.0.jar
